name: cool_gadgets
description: "Cool Gadgets for..."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ####### ####### #######
  back_button_interceptor: ^7.0.0

  blur: ^3.0.0
  ####### ####### #######


  ####### ####### #######
  cloud_firestore: ^5.0.1

  cupertino_icons: ^1.0.2
  ####### ####### #######


  ####### ####### #######
  fast_cached_network_image: ^1.2.9

  firebase_core: ^3.1.0

  firebase_admin: ^0.2.0
  firebase_app_check: ^0.3.0+1

  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1

  flutter_flip_card: ^0.0.4

  flutter_html: ^3.0.0-beta.2

  flutter_rating_stars: ^1.0.3+4
  ####### ####### #######


  ####### ####### #######
  get: ^4.6.6
  ####### ####### #######



  ####### ####### #######
  http: ^0.13.6
  ####### ####### #######


  ####### ####### #######
  indexed: ^0.0.8
  ####### ####### #######


  ####### ####### #######
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  ####### ####### #######



  ####### ####### #######
  shaped_image:
    path: 'X:\Xlutter\Libraries\shaped_image'
  share_plus: ^6.3.4

  shared_preferences: ^2.2.2

  simple_rich_text: ^2.0.49

  smooth_scroll_multiplatform: ^1.0.8
  ####### ####### #######


  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######


  ####### ####### #######
  widget_mask: ^1.0.0+0

  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.otf