// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlvbOaIEFy4uCazxugGo7cWx7aVG-gn3U',
    appId: '1:826703621301:web:7fde8fdb80ee8400fe22fc',
    messagingSenderId: '826703621301',
    projectId: 'cool-gadgets-for',
    authDomain: 'cool-gadgets-for.firebaseapp.com',
    storageBucket: 'cool-gadgets-for.appspot.com',
    measurementId: 'G-7W33DSX0WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OST6T9UhFXnjy_8IOekGAygjh_FCo6Y',
    appId: '1:826703621301:android:0ab4530cc3d40e33fe22fc',
    messagingSenderId: '826703621301',
    projectId: 'cool-gadgets-for',
    storageBucket: 'cool-gadgets-for.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-XpOwZUVTSRaA8BToa36K2zhwLl5df-U',
    appId: '1:826703621301:ios:6bf7aac6a51202a2fe22fc',
    messagingSenderId: '826703621301',
    projectId: 'cool-gadgets-for',
    storageBucket: 'cool-gadgets-for.appspot.com',
    iosBundleId: 'co.geeksempire.coolgadgetsfor',
  );
}
